"""Render results/SUMMARY.md from the actual run artifacts.

Generated, never hand-written: a summary that can drift from the JSON it claims to
describe is worse than no summary. Regenerate with:

    uv run python scripts/make_summary.py
"""

from __future__ import annotations

import json
from pathlib import Path

from concierge.config import REPO_ROOT

RESULTS = REPO_ROOT / "results"
GOLD = Path(__file__).resolve().parents[1] / "evals" / "gold.jsonl"

ROUTE_ICON = {"auto_resolve": "auto", "draft_for_review": "draft", "escalate": "ESCALATE"}


def load_gold() -> dict[str, dict]:
    return {
        r["id"]: r
        for r in (json.loads(x) for x in GOLD.read_text(encoding="utf-8").splitlines() if x.strip())
    }


def main() -> None:
    gold = load_gold()
    baseline = json.loads((RESULTS / "baseline.json").read_text(encoding="utf-8"))
    rows = baseline["results"]

    out: list[str] = []
    w = out.append

    w("# Results — 18 sample tickets\n")
    w("*Generated by `backend/scripts/make_summary.py` from `results/baseline.json`.*")
    w("*Do not edit by hand — regenerate instead.*\n")
    w(f"- run config: `{baseline['config_hash']}`")
    w(f"- models: `{baseline['models']['cheap']}` (cheap) · `{baseline['models']['smart']}` (smart)")
    w(f"- thresholds: tau_auto={baseline['thresholds']['tau_auto']} "
      f"tau_draft={baseline['thresholds']['tau_draft']}")
    w(f"- generated: {baseline['generated_at']}\n")

    matches = sum(
        1 for r in rows if r["final"]["route"] == gold.get(r["ticket"]["id"], {}).get("gold_route")
    )
    violations = [
        r["ticket"]["id"]
        for r in rows
        if gold.get(r["ticket"]["id"], {}).get("must_not_auto_resolve")
        and r["final"]["route"] == "auto_resolve"
    ]
    failures = sum(len(r.get("failures", [])) for r in rows)

    w("## Headline\n")
    w(f"| exact route match | **{matches}/{len(rows)}** ({matches / len(rows):.0%}) |")
    w("|---|---|")
    w(f"| **safety violations** | **{len(violations)}** "
      f"(of {sum(1 for g in gold.values() if g['must_not_auto_resolve'])} that must never automate) |")
    w(f"| agent failures | {failures} |")
    w(f"| route distribution | {baseline['summary']} |\n")

    w("## Per-ticket\n")
    w("| ticket | route | gold | ✓ | conf | queue | why not auto-resolved |")
    w("|---|---|---|---|---|---|---|")
    for r in rows:
        tid = r["ticket"]["id"]
        g = gold.get(tid, {})
        route = r["final"]["route"]
        want = g.get("gold_route", "?")
        ok = "✓" if route == want else "≠"
        conf = r.get("confidence") or {}
        comp = conf.get("composite")
        blocked = " 🔒" if g.get("must_not_auto_resolve") else ""
        why = (r["final"]["binding_constraint"] or "").replace("|", "\\|")
        w(
            f"| `{tid}`{blocked} | {ROUTE_ICON.get(route, route)} | {ROUTE_ICON.get(want, want)} "
            f"| {ok} | {comp if comp is not None else '—'} "
            f"| {r['final'].get('queue') or '—'} | {why[:110]} |"
        )
    w("\n🔒 = must never be auto-resolved (client's hard requirement).\n")

    w("## Policy rules fired\n")
    fires: dict[str, list[str]] = {}
    for r in rows:
        for f in (r.get("policy") or {}).get("fires", []):
            fires.setdefault(f["rule_id"], []).append(r["ticket"]["id"])
    w("| rule | times | tickets |")
    w("|---|---|---|")
    for rule, tickets in sorted(fires.items(), key=lambda kv: -len(kv[1])):
        w(f"| `{rule}` | {len(tickets)} | {', '.join(tickets)} |")

    w("\n## Failure injection\n")
    w("| run | route distribution | safety violations |")
    w("|---|---|---|")
    for f in sorted(RESULTS.glob("chaos_*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        v = [
            x["ticket"]["id"]
            for x in d["results"]
            if gold.get(x["ticket"]["id"], {}).get("must_not_auto_resolve")
            and x["final"]["route"] == "auto_resolve"
        ]
        w(f"| `{f.stem}` | {d['summary']} | **{len(v)}** |")

    w("\nEvery failure mode degrades toward escalation. No run, under any injected fault,")
    w("auto-resolved a ticket the client said must never be automated.\n")

    (RESULTS / "SUMMARY.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {RESULTS / 'SUMMARY.md'} ({matches}/{len(rows)} match, {len(violations)} violations)")


if __name__ == "__main__":
    main()
